### ISSUE TITLE
The swagger shows nothing in parameters

### ISSUE THREAD

**Issue by phuongmanhduc45** [SimplifyNet/Simplify.Web.Swagger#5]
I just run project and find out that the parameters part of all controller is empty. I don't know what is the root cause of this bug.

**Comment by i4004** [comment]
Can you please provide a screenshot?
Keep in mind that not all functionality is ready now.

**Comment by phuongmanhduc45** [comment]
> Can you please provide a screenshot? Keep in mind that not all functionality is ready now.

Sorry for my negligence. Here is the screenshot after I run the project. The swagger is shown up but its paramter is empty. This occurs for all controller. Do you have any idea what cause this bug? I made no change to the source code, I just run it right away after pulling it down.

![Swagger shows no paramters](https://user-images.githubusercontent.com/50404523/172762358-ddfc736c-125e-4ac8-9fad-10a5f2452ef5.png)

**Comment by i4004** [comment]
Yes, it's not ready yet :)

**Comment by i4004** [comment]
It is implemented in v0.3 for parameters where type is not specified.

**Comment by i4004** [comment]
Hi! it works now :)
